application: lilydjwg # that's the *** part in ***.appspost.com.
version: test
runtime: python
api_version: 1

handlers:
- url: /_ah/xmpp/.*
  script: chatmain.py
- url: /_test/memcache
  script: memcachetest.py
- url: /_admin/clean.*
  script: clean.py
  login: admin
- url: /
  static_files: README.html
  upload: README.html
- url: /css
  static_dir: css
- url: /img
  static_dir: img

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe

builtins:
- datastore_admin: on
